### ISSUE TITLE
Feature: add an algolia search bar to the docs

### ISSUE THREAD

**Issue by alarbada** [ConduitIO/conduit-site#44]
### Feature description

Just like the meroxa docs:
https://docs.meroxa.com/

It makes the docs much more approachable.

**Comment by simonl2002** [comment]
Will assess this after 0.9.0 update to docs.

**Comment by raulb** [comment]
@alarbada was coming to this repo to open an issue like this one. I certainly agree with this one!

**Comment by raulb** [comment]
Just applied to Algolia search



![Image](https://github.com/ConduitIO/conduit-site/assets/306015/08ed697e-69df-4edc-bb4a-2ba91149c459)

**Comment by raulb** [comment]
> Hi there 👋
> 
> Thanks for your interest and trust in Algolia DocSearch. We've received your request for https://conduit.io/docs/, and will get back to you soon.
> 
> DocSearch is built in two parts:
> - A crawler which we run in our own infrastructure every week (configurable). It follows every link in your website and extracts content from every page it traverses. It then pushes this content to an > Algolia index. (Read more: https://www.algolia.com/doc/tools/crawler/getting-started/overview/ )
> - A JavaScript snippet to be inserted in your website that will bind this Algolia index to your search input and display its results in a modal UI. (Read more: https://github.com/algolia/docsearch )
> 
> If you want to find more details on how DocSearch works, take a look at the docs: https://docsearch.algolia.com/
> 
> Meanwhile, let us know if you have any other questions.
> 
> Have a great day,
> The DocSearch team.
> 
> DocSearch is powered by Algolia. See more at https://www.algolia.com/

**Comment by raulb** [comment]
We can search! https://conduit.io/docs/search/
